// <auto-generated />
using System;
using CourseRegistrationWebPage.Models.Repos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseRegistrationWebPage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221205195353_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CourseRegistrationWebPage.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Course_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Course_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Course_Name = "Dark Arts Defense",
                            Course_Number = "T0504",
                            Description = "Students will learn how to defend themselves from dark magic"
                        },
                        new
                        {
                            ID = 2,
                            Course_Name = "Potions",
                            Course_Number = "T0506",
                            Description = "Students will learn how to create potions"
                        },
                        new
                        {
                            ID = 3,
                            Course_Name = "Animal Care",
                            Course_Number = "T0509",
                            Description = "Students will learn how to care for magic animals"
                        },
                        new
                        {
                            ID = 4,
                            Course_Name = "Transfiguration",
                            Course_Number = "T0510",
                            Description = "Students will learn how to transform themselves"
                        },
                        new
                        {
                            ID = 5,
                            Course_Name = "Herbology",
                            Course_Number = "T0512",
                            Description = "Students will study the medical properties of herbs"
                        });
                });

            modelBuilder.Entity("CourseRegistrationWebPage.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Course_ID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("Course_ID");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            ID = 10,
                            Course_ID = 2,
                            Email = "S.Snape@gmail.com",
                            First_Name = "Severus",
                            Last_Name = "Snape"
                        },
                        new
                        {
                            ID = 11,
                            Course_ID = 1,
                            Email = "L.Lupin@gmail.com",
                            First_Name = "Remus",
                            Last_Name = "Lupin"
                        },
                        new
                        {
                            ID = 12,
                            Course_ID = 3,
                            Email = "R.Hagrid@gmail.com",
                            First_Name = "Rubeus",
                            Last_Name = "Hagrid"
                        },
                        new
                        {
                            ID = 13,
                            Course_ID = 4,
                            Email = "M.McGonagall@gmail.com",
                            First_Name = "Minerva",
                            Last_Name = "McGonagall"
                        });
                });

            modelBuilder.Entity("CourseRegistrationWebPage.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Course_ID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("Course_ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 100,
                            Course_ID = 2,
                            Email = "H.Potter@gmail.com",
                            First_Name = "Harry",
                            Last_Name = "Potter",
                            Phone = "123-456-7899"
                        },
                        new
                        {
                            ID = 101,
                            Course_ID = 3,
                            Email = "R.Weasley@gmail.com",
                            First_Name = "Ron",
                            Last_Name = "Weasley",
                            Phone = "987-654-3211"
                        },
                        new
                        {
                            ID = 102,
                            Course_ID = 2,
                            Email = "H.Granger@gmail.com",
                            First_Name = "Hermione",
                            Last_Name = "Granger",
                            Phone = "963-852-7411"
                        },
                        new
                        {
                            ID = 103,
                            Course_ID = 1,
                            Email = "D.Malfoy@gmail.com",
                            First_Name = "Draco",
                            Last_Name = "Malfoy",
                            Phone = "741-852-9633"
                        },
                        new
                        {
                            ID = 104,
                            Course_ID = 4,
                            Email = "N.Longbottom@gmail.com",
                            First_Name = "Neville",
                            Last_Name = "Longbottom",
                            Phone = "852-963-7532"
                        });
                });

            modelBuilder.Entity("CourseRegistrationWebPage.Models.Instructor", b =>
                {
                    b.HasOne("CourseRegistrationWebPage.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Course_ID");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseRegistrationWebPage.Models.Student", b =>
                {
                    b.HasOne("CourseRegistrationWebPage.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("Course_ID");

                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
